- generate-database:
    batch_size: 64
    camera_fov: 20.0
    disable_progress_bar: true
    embedding_type: iresnet50
    git:
      branch: master
      version: 7f1f30ae783d771934fe005c9981f46b710a5505
    network_type: stylegan2-256
    no_images: true
    num_identities: 10000
    postprocessor_config: null
    root_directory: $synthetic_database_path/sg2_n10k_arc_r14_lang_v1/
    seed: null
    truncation_psi: 0.7
- create-references:
    algorithm: langevin
    ict: 1.4
    langevin_checkpoint_iter: 5
    langevin_constant_embeddings: null
    langevin_iterations: 50
    langevin_latent_force: 0.1
    langevin_random_force: 0.01
    langevin_repulsion_coefficient: 1.0
    langevin_repulsion_radius: 1.4
    langevin_timestep: -0.3
    langevin_viscous_coefficient: 1.0
    neutralization: false
    repulse: 0.0
- generate-database:
    batch_size: 64
    camera_fov: 20.0
    disable_progress_bar: true
    embedding_type: iresnet50
    git:
      branch: master
      version: ac81752945535067b45a8d7a93a0734b8a354825
    network_type: stylegan2-256
    no_images: false
    num_identities: 10000
    postprocessor_config: arcface
    root_directory: $synthetic_database_path/sg2_n10k_arc_r14_lang_v1
    seed: null
    truncation_psi: 0.7
- generate-images:
    image_directory: null
